#! /bin/bash 

host="$(hostname)"
os='Linux'	# I'd just like to interject for a moment...
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages='unknown'
shell="$(basename "${SHELL}")"


echo $host 
